"""add stock last_fetched_at

Revision ID: 35f5b162beb2
Revises: 7b7944378e01
Create Date: 2026-07-04 09:39:01.174861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f5b162beb2'
down_revision: Union[str, Sequence[str], None] = '7b7944378e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'last_fetched_at')
    # ### end Alembic commands ###
