"""add isin and cap_category to stocks

Revision ID: 6875dce660d0
Revises: 83f604b4d871
Create Date: 2026-07-03 20:33:22.465138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6875dce660d0'
down_revision: Union[str, Sequence[str], None] = '83f604b4d871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('isin', sa.String(length=16), nullable=True))
    op.add_column('stocks', sa.Column('cap_category', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_stocks_isin'), 'stocks', ['isin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_isin'), table_name='stocks')
    op.drop_column('stocks', 'cap_category')
    op.drop_column('stocks', 'isin')
    # ### end Alembic commands ###
