"""add confidence layer columns

Revision ID: 7b7944378e01
Revises: f93783e64c6c
Create Date: 2026-07-04 07:37:07.779335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b7944378e01'
down_revision: Union[str, Sequence[str], None] = 'f93783e64c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composite_score_history', sa.Column('score_stderr_eff', sa.Float(), nullable=True))
    op.add_column('composite_score_history', sa.Column('lcb', sa.Float(), nullable=True))
    op.add_column('composite_score_history', sa.Column('factor_version', sa.String(length=16), nullable=True))
    op.add_column('composite_scores', sa.Column('axis_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('composite_scores', sa.Column('confidence_tier', sa.String(length=16), nullable=True))
    op.add_column('composite_scores', sa.Column('score_stderr_eff', sa.Float(), nullable=True))
    op.add_column('composite_scores', sa.Column('lcb', sa.Float(), nullable=True))
    op.add_column('composite_scores', sa.Column('factor_version', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_composite_scores_lcb'), 'composite_scores', ['lcb'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composite_scores_lcb'), table_name='composite_scores')
    op.drop_column('composite_scores', 'factor_version')
    op.drop_column('composite_scores', 'lcb')
    op.drop_column('composite_scores', 'score_stderr_eff')
    op.drop_column('composite_scores', 'confidence_tier')
    op.drop_column('composite_scores', 'axis_scores')
    op.drop_column('composite_score_history', 'factor_version')
    op.drop_column('composite_score_history', 'lcb')
    op.drop_column('composite_score_history', 'score_stderr_eff')
    # ### end Alembic commands ###
