"""gin index on stocks.universe

Revision ID: 83f604b4d871
Revises: f7ed67042571
Create Date: 2026-07-03 19:47:10.845212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f604b4d871'
down_revision: Union[str, Sequence[str], None] = 'f7ed67042571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stocks_universe_gin', 'stocks', ['universe'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocks_universe_gin', table_name='stocks', postgresql_using='gin')
    # ### end Alembic commands ###
