"""add data_quality_reports table

Revision ID: a6faff6fe9d1
Revises: bd60b5f414b2
Create Date: 2026-07-03 21:47:49.541831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6faff6fe9d1'
down_revision: Union[str, Sequence[str], None] = 'bd60b5f414b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('missing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_overall_score'), 'data_quality_reports', ['overall_score'], unique=False)
    op.create_index(op.f('ix_data_quality_reports_stock_id'), 'data_quality_reports', ['stock_id'], unique=False)
    op.create_index('ix_dq_stock_checked', 'data_quality_reports', ['stock_id', 'checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dq_stock_checked', table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_stock_id'), table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_overall_score'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    # ### end Alembic commands ###
