"""add fetch_failures to stocks

Revision ID: b810c6f6884d
Revises: bba617b87608
Create Date: 2026-07-03 23:41:53.139020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b810c6f6884d'
down_revision: Union[str, Sequence[str], None] = 'bba617b87608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('fetch_failures', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'fetch_failures')
    # ### end Alembic commands ###
