"""add screener and quarterly_financials to snapshots

Revision ID: bba617b87608
Revises: 6875dce660d0
Create Date: 2026-07-03 20:53:19.998591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bba617b87608'
down_revision: Union[str, Sequence[str], None] = '6875dce660d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_snapshots', sa.Column('quarterly_financials', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('stock_snapshots', sa.Column('screener', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_snapshots', 'screener')
    op.drop_column('stock_snapshots', 'quarterly_financials')
    # ### end Alembic commands ###
