"""add daily_prices ohlcv table

Revision ID: bd60b5f414b2
Revises: b810c6f6884d
Create Date: 2026-07-04 07:04:17.377283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd60b5f414b2'
down_revision: Union[str, Sequence[str], None] = 'b810c6f6884d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_daily_price_stock_date')
    )
    op.create_index('ix_daily_price_stock_date', 'daily_prices', ['stock_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_prices_stock_id'), 'daily_prices', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_prices_stock_id'), table_name='daily_prices')
    op.drop_index('ix_daily_price_stock_date', table_name='daily_prices')
    op.drop_table('daily_prices')
    # ### end Alembic commands ###
