"""unique composite per stock

Revision ID: f11b92774a9e
Revises: a6faff6fe9d1
Create Date: 2026-07-04 06:24:59.456621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11b92774a9e'
down_revision: Union[str, Sequence[str], None] = 'a6faff6fe9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Defensive dedupe: collapse any pre-existing duplicate composites (left by the
    # old delete-then-insert under concurrency) to the newest row per stock BEFORE
    # the unique constraint is added, so the migration can't fail on dirty data.
    op.execute(
        """
        DELETE FROM composite_scores a
        USING composite_scores b
        WHERE a.stock_id = b.stock_id AND a.id < b.id
        """
    )
    op.create_unique_constraint('uq_composite_stock', 'composite_scores', ['stock_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_composite_stock', 'composite_scores', type_='unique')
    # ### end Alembic commands ###
