"""initial schema

Revision ID: f7ed67042571
Revises: 
Create Date: 2026-07-03 19:31:03.967045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7ed67042571'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_type'), 'job_runs', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('nse_symbol', sa.String(length=64), nullable=True),
    sa.Column('yf_symbol', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=256), nullable=True),
    sa.Column('listing_date', sa.String(length=32), nullable=True),
    sa.Column('issue_price', sa.Float(), nullable=True),
    sa.Column('ipo_mcap_cr', sa.Float(), nullable=True),
    sa.Column('screener_url', sa.String(length=512), nullable=True),
    sa.Column('universe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_status'), 'stocks', ['status'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('composite_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('persona_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('consensus_recommendation', sa.String(length=16), nullable=True),
    sa.Column('recommendation_counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('analysis_coverage', sa.Integer(), nullable=True),
    sa.Column('total_personas', sa.Integer(), nullable=True),
    sa.Column('scoring_method', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composite_scores_composite_score'), 'composite_scores', ['composite_score'], unique=False)
    op.create_index(op.f('ix_composite_scores_stock_id'), 'composite_scores', ['stock_id'], unique=False)
    op.create_table('stock_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetch_status', sa.String(length=32), nullable=True),
    sa.Column('data_quality', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('financials', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('balance_sheet', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cashflow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('history_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ipo_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'content_hash', name='uq_snapshot_stock_hash')
    )
    op.create_index('ix_snapshot_stock_captured', 'stock_snapshots', ['stock_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_stock_snapshots_content_hash'), 'stock_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_stock_snapshots_stock_id'), 'stock_snapshots', ['stock_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=True),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('key_strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('key_risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('red_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detailed_analysis', sa.Text(), nullable=True),
    sa.Column('metrics_evaluated', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['stock_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_persona'), 'analyses', ['persona'], unique=False)
    op.create_index(op.f('ix_analyses_stock_id'), 'analyses', ['stock_id'], unique=False)
    op.create_index('ix_analysis_data_hash', 'analyses', ['data_hash'], unique=False)
    op.create_index('ix_analysis_stock_persona', 'analyses', ['stock_id', 'persona'], unique=False)
    op.create_table('stock_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=64), nullable=True),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_analysis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_insights_stock_id'), 'stock_insights', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_insights_stock_id'), table_name='stock_insights')
    op.drop_table('stock_insights')
    op.drop_index('ix_analysis_stock_persona', table_name='analyses')
    op.drop_index('ix_analysis_data_hash', table_name='analyses')
    op.drop_index(op.f('ix_analyses_stock_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_persona'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_stock_snapshots_stock_id'), table_name='stock_snapshots')
    op.drop_index(op.f('ix_stock_snapshots_content_hash'), table_name='stock_snapshots')
    op.drop_index('ix_snapshot_stock_captured', table_name='stock_snapshots')
    op.drop_table('stock_snapshots')
    op.drop_index(op.f('ix_composite_scores_stock_id'), table_name='composite_scores')
    op.drop_index(op.f('ix_composite_scores_composite_score'), table_name='composite_scores')
    op.drop_table('composite_scores')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_status'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_type'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
