"""add composite_score_history

Revision ID: f93783e64c6c
Revises: f11b92774a9e
Create Date: 2026-07-04 07:08:38.348632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f93783e64c6c'
down_revision: Union[str, Sequence[str], None] = 'f11b92774a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('information_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('persona_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('axis_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence_tier', sa.String(length=16), nullable=True),
    sa.Column('consensus_recommendation', sa.String(length=16), nullable=True),
    sa.Column('analysis_coverage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'as_of_date', name='uq_score_history_stock_day')
    )
    op.create_index(op.f('ix_composite_score_history_stock_id'), 'composite_score_history', ['stock_id'], unique=False)
    op.create_index('ix_score_history_stock_asof', 'composite_score_history', ['stock_id', 'as_of_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_history_stock_asof', table_name='composite_score_history')
    op.drop_index(op.f('ix_composite_score_history_stock_id'), table_name='composite_score_history')
    op.drop_table('composite_score_history')
    # ### end Alembic commands ###
